// <auto-generated />
using Rhino;
using Rhino.Display;
using Rhino.DocObjects;
using Rig;

namespace Excavator;

public class Document : Rig.Document
{
    public sealed class LogoLetter(RhinoDoc doc, ObjectChangeHub objectChangeHub) : RhinoInput("LogoLetter", doc, objectChangeHub);
    public sealed class LogoLetters(RhinoDoc doc, ObjectChangeHub objectChangeHub) : RhinoInput("LogoLetter", doc, objectChangeHub);

    public class Layers : LayersBase
    {
        public static Layer Body => FindByName("Body");
        public static Layer Glass => FindByName("Glass");
        public static Layer Track => FindByName("Track");
    }

    public class Materials : MaterialsBase
    {
        public static Material Body => FindByName("Body");
        public static Material Glass => FindByName("Glass");
        public static Material Track => FindByName("Track");
    }

    public class DimStyles : DimStylesBase
    {
        public static DimensionStyle Default => FindByName("Default");
    }

    public class Linetypes : LinetypesBase
    {
        public static Linetype Border => FindByName("Border");
        public static Linetype Center => FindByName("Center");
        public static Linetype DashDot => FindByName("DashDot");
        public static Linetype Dashed => FindByName("Dashed");
        public static Linetype Dots => FindByName("Dots");
        public static Linetype Hidden => FindByName("Hidden");
    }
}
