// <auto-generated />
using Rhino;
using Rhino.Display;
using Rhino.DocObjects;
using Rig;

namespace Extrusion;

public class Document : Rig.Document
{
    public sealed class Profile(RhinoDoc doc, ObjectChangeHub objectChangeHub) : RhinoInput("Profile", doc, objectChangeHub);
    public sealed class Profiles(RhinoDoc doc, ObjectChangeHub objectChangeHub) : RhinoInput("Profile", doc, objectChangeHub);

    public class Layers : LayersBase
    {
        public static Layer Default => FindByName("Default");
        public static Layer Layer_01 => FindByName("Layer 01");
        public static Layer Layer_02 => FindByName("Layer 02");
        public static Layer Layer_03 => FindByName("Layer 03");
        public static Layer Layer_04 => FindByName("Layer 04");
        public static Layer Layer_05 => FindByName("Layer 05");
    }

    public class DimStyles : DimStylesBase
    {
        public static DimensionStyle Centimeters_Architectural => FindByName("Centimeters Architectural");
        public static DimensionStyle Centimeters_Large => FindByName("Centimeters Large");
        public static DimensionStyle Centimeters_Small => FindByName("Centimeters Small");
        public static DimensionStyle Engrave => FindByName("Engrave");
    }
}
